FROM python:3.10-alpine
ENV PYTHONUNBUFFERED=1

ARG ENV
ARG SECRET_KEY
ARG DB_NAME
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT
ARG CORS_ALLOWED_ORIGINS
ARG HOST
ARG HOST_FRONTEND
ARG DEFAULT_TENANT_HOST
ARG CELERY_BROKER_URL
ARG JWT_PRIVATE_KEY
ARG JWT_PUBLIC_KEY
ARG GOOGLE_CALLBACK_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG CONSOLE_SERVICE_URL
ARG ROOT_API_KEY
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_STORAGE_BUCKET_NAME
ARG AWS_REGION
ARG DEFAULT_FROM_EMAIL
ARG EMAIL_HOST_USER
ARG EMAIL_HOST_PASSWORD
ARG REDIS_HOST

# Allows docker to cache installed dependencies between builds
RUN apk add build-base libffi-dev curl
COPY ./auth-service/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./django-common-utils django-common-utils
RUN pip install ../django-common-utils

# Adds our application code to the image
COPY ./auth-service auth-service

WORKDIR /auth-service

EXPOSE 80

ENV DJANGO_SETTINGS_MODULE="auth_service.settings"

ENV ENV=${ENV}
ENV SECRET_KEY=${SECRET_KEY}
ENV DB_NAME=${DB_NAME}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
ENV HOST=${HOST}
ENV HOST_FRONTEND=${HOST_FRONTEND}
ENV DEFAULT_TENANT_HOST=${DEFAULT_TENANT_HOST}
ENV CELERY_BROKER_URL=${CELERY_BROKER_URL}
ENV JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
ENV JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
ENV GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV CONSOLE_SERVICE_URL=${CONSOLE_SERVICE_URL}
ENV ROOT_API_KEY=${ROOT_API_KEY}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
ENV AWS_REGION=${AWS_REGION}
ENV DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
ENV EMAIL_HOST_USER=${EMAIL_HOST_USER}
ENV EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
ENV REDIS_HOST=${REDIS_HOST}


RUN ["chmod", "+x", "./docker-entrypoint.sh"]

# Run the production server
ENTRYPOINT ["./docker-entrypoint.sh"]
