# Generated by Django 5.0.6 on 2024-06-24 09:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), size=None
                    ),
                ),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("UPDATE_ORGANIZATION", "Update Organization"),
                                ("DELETE_ORGANIZATION", "Delete Organization"),
                                ("READ_ORGANIZATION_ROLE", "Read Organization Role"),
                                (
                                    "CREATE_ORGANIZATION_ROLE",
                                    "Create Organization Role",
                                ),
                                (
                                    "UPDATE_ORGANIZATION_ROLE",
                                    "Update Organization Role",
                                ),
                                (
                                    "DELETE_ORGANIZATION_ROLE",
                                    "Delete Organization Role",
                                ),
                                (
                                    "READ_ORGANIZATION_MEMBER",
                                    "Read Organization Member",
                                ),
                                (
                                    "INVITE_ORGANIZATION_MEMBER",
                                    "Invite Organization Member",
                                ),
                                (
                                    "UPDATE_ORGANIZATION_MEMBER_ROLE",
                                    "Update Organization Member Role",
                                ),
                                (
                                    "REMOVE_ORGANIZATION_MEMBER",
                                    "Remove Organization Member",
                                ),
                            ],
                            max_length=256,
                        ),
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpaceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("policies", models.ManyToManyField(to="space_role.policy")),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_role",
                        to="space.space",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
